routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::middleware(['auth'])->group(function () {

    Route::get('/', 'HomeController@index')->name('home');

    Route::resource('developers', 'DeveloperController');
    Route::resource('clients', 'ClientController')->middleware('checkAdmin');
    Route::resource('products', 'ProductController');
    Route::resource('admins', 'AdminController')->middleware('checkSuperAdmin');
    Route::resource('users', 'UserController')->middleware('checkSuperAdmin');
    Route::any('kpi', 'KpiController@index')->name('kpi')->middleware('checkAdmin');

    //home
    Route::post('filter_status', 'HomeController@filterStatus')->name('filter.status');
    Route::post('search_home', 'HomeController@searchProduct')->name('search.home');
    Route::post('load_products', 'HomeController@loadProducts');

    //upload product file
    Route::post('uploads/product/file', 'ProductController@uploadFile');
    //delete product file
    Route::post('delete/product/file', 'ProductController@deleteFile');
    //update status
    Route::post('update/product/status/{id}', 'ProductController@updateStatus')->name('update.status');


});

app/Models/Client.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'description', 'avatar'
    ];
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ClientCreateRequest;
use App\Models\Client;
use App\Services\Upload\UploadFileService;
use Illuminate\Http\Request;

class ClientController extends Controller
{

    private $service;

    public function __construct(UploadFileService $service)
    {
        $this->service = $service;
    }

    /**
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Request $request)
    {
        $search = '';
        if ($request->filled('search')){
            $search = $request->input('search');
            $clients = Client::where('name', 'like', '%'.$search.'%')
                ->latest()
                ->paginate(15);
        } else {
            $clients = Client::latest()
                ->paginate(15);
        }
        return view('pages.client.list', compact('clients', 'search'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.client.create');
    }

    /**
     * @param ClientCreateRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(ClientCreateRequest $request)
    {
        $data = [
            'name' => $request->input('name'),
            'email' => $request->input('email'),
            'description' => $request->input('description'),
        ];
        if($request->filled('avatar')){
            $avatar = $this->service->uploadAvatarClient($request);
            $data['avatar'] = $avatar;
        }
        $client = Client::create($data);

        return back()
            ->with('success',['text'=>'Client Successfully Added!', 'id'=>$client->id]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $client = Client::find($id);
        return view('pages.client.edit', compact('client'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $client = Client::find($id);
        $data = [
            'name' => $request->input('name'),
            'email' => $request->input('email'),
            'description' => $request->input('description'),
        ];

        if($request->filled('del_avatar')){
            $this->service->deleteFile($client->avatar);
            $client->avatar = null;
        }
        if($request->filled('avatar')){
            $avatar = $this->service->uploadAvatar($request);
            $data['avatar'] = $avatar;
        }

        $client->update($data);

        return back()
            ->with('success',['text'=>'Client Successfully Added!', 'id'=>$client->id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $client = Client::find($id);
        $this->service->deleteFile($client->avatar);
        $client->delete();

        return redirect('clients')->with('success','Client deleted successfully');
    }
}

resources/views/pages/client/create.blade.php
@extends('layouts.layouts')

@section('content')

    @if (session('success'))
        <script>
            show_modal = true;
        </script>
    @else
        <script>
            show_modal = false;
        </script>
    @endif
    <div class="row">
        <div class="col-md-6">
            <div>
                <h4>{{ __('Add New client') }}</h4>
            </div>
            <div class="x_panel">
                <div class="x_title">
                    <h6>Details</h6>
                </div>
                <div class="x_content">
                    <form id="create-client-form" action="{{ route('clients.store') }}" method="POST" style="max-width: 800px">
                        {{ csrf_field() }}
                        <input type="hidden" name="avatar" value="{{ old('avatar') }}" id="input_avatar">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="photo_wrapper">
                                    <div class="img_block text-center">
                                        <img id="img_avatar"
                                             class="img_avatar"
                                             src="{{ empty(old('avatar'))? asset('uploads/users/default_avatar.png'): old('avatar') }}"
                                             alt="avatar"
                                        >
                                    </div>
                                    <div class="button_block">
                                        <input type="file" id="file_upload" name="file" accept="image/jpeg,image/png" style="display: none">
                                        <label for="file_upload" id="button_file_upload" class="btn btn-secondary btn-sm"><i class="fa fa-pencil"></i></label>
                                        <button class="btn btn-secondary btn-sm"
                                                id="delete_file"
                                                type="button"
                                                data-default_avatar="{{ asset('uploads/users/default_avatar.png') }}"
                                        ><i class="fa fa-trash-o"></i></button>
                                    </div>
                                    <div id="error_block_file"></div>
                                </div>
                            </div>
                            <div class="col-md-8">
                                <div class="form-group">
                                    <label for="name">Name * </label>
                                    <input type="text" id="name" name="name" class="form-control" value="{{ old('name') }}" />
                                    <span class="text-danger">{{ $errors->first('name') }}</span>
                                </div>
                                <div class="form-group">
                                    <label for="email">Email * </label>
                                    <input type="email" id="email" class="form-control" name="email" value="{{ old('email') }}" />
                                    <span class="text-danger">{{ $errors->first('email') }}</span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>Description(20 chars min):</label>
                                    <textarea name="description" class="form-control" placeholder="Description of good" >{{ old('description') }}</textarea>
                                    <span class="text-danger">{{ $errors->first('description') }}</span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="button_block">
                                    <a href="{{ route('clients.index') }}" class="btn btn-danger">Cancel</a>
                                    <button class="btn btn-primary" type="submit">Save</button>
                                </div>
                                <div class="alert_block_form" id="alert_block_form"></div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    @include('common.modals.croppie_modal')
    @include('common.modals.size_modal')
    @include('common.modals.client_add_modal')

@endsection

resources/views/pages/client/edit.blade.php
@extends('layouts.layouts')

@section('content')

    @if (session('success'))
        <script>
            show_modal = true;
        </script>
    @else
        <script>
            show_modal = false;
        </script>
    @endif
    <div class="row">
        <div class="col-md-6">
            <div>
                <h4>{{ __('Add New client') }}</h4>
            </div>
            <div class="x_panel">
                <div class="x_title">
                    <h6>Details</h6>
                </div>
                <div class="x_content">
                    <form id="update-client-form" action="{{ route('clients.update', $client) }}" method="POST" style="max-width: 800px">
                        {{ csrf_field() }}
                        {{ method_field('PATCH') }}
                        <input type="hidden" name="avatar" value="{{ old('avatar') }}" id="input_avatar">
                        <input type="hidden" name="del_avatar" value="{{old('del_avatar')}}" id="del_avatar" >
                        <input type="hidden" name="user_id" value="{{$client->id}}" >
                        <div class="row">
                            <div class="col-md-4">
                                <div class="photo_wrapper">
                                    <div class="img_block text-center">
                                        <img id="img_avatar"
                                             class="img_avatar"
                                             src="{{ empty($client->avatar)? asset('uploads/users/default_avatar.png'): asset($client->avatar) }}"
                                             alt="avatar"
                                        >
                                    </div>
                                    <div class="button_block">
                                        <input type="file" id="file_upload" name="file" accept="image/jpeg,image/png" style="display: none">
                                        <label for="{{empty($client->avatar)? 'file_upload': '' }}" id="button_file_upload" class="btn btn-secondary btn-sm"><i class="fa fa-pencil"></i></label>
                                        <button class="btn btn-secondary btn-sm update_user"
                                                id="delete_file"
                                                type="button"
                                                data-default_avatar="{{ asset('uploads/users/default_avatar.png') }}"
                                        ><i class="fa fa-trash-o"></i></button>
                                    </div>
                                    <div id="error_block_file"></div>
                                </div>
                            </div>
                            <div class="col-md-8">
                                <div class="form-group">
                                    <label for="name">Name * </label>
                                    <input type="text" id="name" name="name" class="form-control" value="{{ $client->name }}" />
                                    <span class="text-danger">{{ $errors->first('name') }}</span>
                                </div>
                                <div class="form-group">
                                    <label for="email">Email * </label>
                                    <input type="email" id="email" class="form-control" name="email" value="{{ $client->email }}" />
                                    <span class="text-danger">{{ $errors->first('email') }}</span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>Description(20 chars min):</label>
                                    <textarea name="description" class="form-control" placeholder="Description of good" >{{ $client->description }}</textarea>
                                    <span class="text-danger">{{ $errors->first('description') }}</span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="button_block">
                                    <a href="{{ route('clients.index') }}" class="btn btn-danger">Cancel</a>
                                    <button class="btn btn-primary" type="submit">Save</button>
                                </div>
                                <div class="alert_block_form" id="alert_block_form"></div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    @include('common.modals.croppie_modal')
    @include('common.modals.size_modal')
    @include('common.modals.client_add_modal')

@endsection

resources/views/pages/client/list.blade.php
@extends('layouts.layouts')

@section('content')

    @if (session('success'))
        <div class="alert alert-success status_alert" id="status_alert">
            {{ session('success') }}
        </div>
    @endif
<div class="page-suppliers">
    <div class="page-title">
        <div class="title_left">
            <h3>{{__('List of clients')}}</h3>
        </div>
        <div class="title_right">
            <div class="row">
                <div class="col-md-12">
                    <form action="{{ route('clients.index') }}" method="get">
                        <div class="form-group pull-right top_search">
                            <div class="input-group">
                                <input type="text" class="form-control" value="{{ $search }}" name="search" placeholder="Search for...">
                                <span class="input-group-btn">
                              <button class="btn btn-default" type="submit">Go!</button>
                            </span>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-md-12">
            <div class="x_panel">
                <div class="row">
                    <div class="col-md-6">
                        @if($clients->isNotEmpty())
                        <div class="align-items-center">
                            @php
                                $count = $clients->count();
                                $perPage = $clients->perpage();
                                $currentPage = $clients->currentPage();
                                $total = $clients->total();
                                $showing = $currentPage == 1? 1: $perPage * ($currentPage-1);
                            @endphp
                            <span style="margin-right: 5px;"> Showing {{ $showing  }} - {{ $currentPage == 1? $count: $showing+$count }} of {{ $total }}  Clients</span>
                        </div>
                        @endif
                    </div>
                    <div class="col-md-6">
                        <a href="{{route('clients.create')}}" class="btn btn-sm btn-primary pull-right" id="add_supplier">{{__('Add New client')}}</a>
                    </div>

                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                @if($clients->isNotEmpty())
                <!-- start project list -->
                    <table class="table table-striped projects">
                        <thead>
                        <tr>
                            <th style="width: 15%;" >Avatar</th>
                            <th>Name</th>
                            <th>Email</th>

                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($clients as $client)
                        <tr>
                            <td><img src="{{ isset($client->avatar)? asset($client->avatar) : asset('uploads/users/default_avatar.png') }}" alt="" style="width: 60px;"></td>
                            <td>{{$client->name}}</td>
                            <td>{{$client->email}}</td>
                            <td>
                                <div class="td_actions">
                                    <a href="{{ route('clients.edit',$client->id)}}" class="btn btn-primary btn-xs edit_post" ><i class="fa fa-pencil"></i></a>
                                    <form action="{{ route('clients.destroy', $client->id)}}" method="post">
                                        {{ csrf_field() }}
                                        @method('DELETE')
                                        <button class="btn btn-danger btn-xs delete_post"><i class="fa fa-trash-o"></i> </button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                        @endforeach
                        </tbody>
                    </table>
                {{ $clients->links() }}
                    <!-- end project list -->
                    @else
                        <div>Nothing found</div>
                    @endif
                </div>
            </div>
        </div>
    </div>

</div>

@endsection