routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::middleware(['auth'])->group(function () {

    Route::get('/', 'HomeController@index')->name('home');

    Route::resource('developers', 'DeveloperController');
    Route::resource('clients', 'ClientController')->middleware('checkAdmin');
    Route::resource('products', 'ProductController');
    Route::resource('admins', 'AdminController')->middleware('checkSuperAdmin');
    Route::resource('users', 'UserController')->middleware('checkSuperAdmin');
    Route::any('kpi', 'KpiController@index')->name('kpi')->middleware('checkAdmin');

    //home
    Route::post('filter_status', 'HomeController@filterStatus')->name('filter.status');
    Route::post('search_home', 'HomeController@searchProduct')->name('search.home');
    Route::post('load_products', 'HomeController@loadProducts');

    //upload product file
    Route::post('uploads/product/file', 'ProductController@uploadFile');
    //delete product file
    Route::post('delete/product/file', 'ProductController@deleteFile');
    //update status
    Route::post('update/product/status/{id}', 'ProductController@updateStatus')->name('update.status');


});

app/Models/Product.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{

    const WEEK_COUNT = 'week_count';
    const WEEK_AVERAGE = 'week_average';
    const WEEK_TIME = 'week_time';
    const WEEK_CRITICAL = 'week_critical';
    const WEEK_OVERTIME = 'week_overtime';

    const TITLES = [
        self::WEEK_COUNT => 'Total Products',
        self::WEEK_AVERAGE => 'Average Time',
        self::WEEK_TIME => 'Products % in Time',
        self::WEEK_CRITICAL => 'Products % Critical',
        self::WEEK_OVERTIME => 'Products % Overtime'
    ];

    protected $fillable = [ 'name', 'description', 'developer_id', 'client_id', 'status', 'status_deadline', 'status_report', 'files', 'start_date' ];

    protected $casts = [
        'status_deadline' => 'array',
        'status_report' => 'array',
        'files' => 'array',
        'start_date' => 'date'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function client(){
        return $this->hasOne(Client::class, 'id', 'client_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function developer(){
        return $this->hasOne(User::class, 'id', 'developer_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function productStatus(){
        return $this->hasOne(Status::class, 'name', 'status');
    }

    public function getDateStatus($seconds){
        $carbon = new Carbon($seconds);

        return $carbon->format('d.m.Y');
    }


}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProductRequest;
use App\Models\Client;
use App\Models\Product;
use App\Models\Status;
use App\Models\User;
use App\Services\Upload\UploadFileService;
use Illuminate\Http\Request;
use Carbon\Carbon;

class ProductController extends Controller
{

    private $service;

    public function __construct(UploadFileService $service)
    {
        $this->middleware('checkAdmin')->only(['index', 'create', 'update', 'store','destroy','edit']);
        $this->service = $service;
    }

    /**
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Request $request)
    {
        $search = '';
        if ($request->filled('search')){
            $search = $request->input('search');
            $products = Product::where('name', 'like', '%'.$search.'%')
                ->latest()
                ->paginate(15);
        } else {
            $products = Product::latest()
                ->paginate(15);
        }
        return view('pages.product.list', compact('products', 'search'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $clients = Client::all();
        $developers = User::where('role', '=', User::ROLE_DEVELOPER)->get();
        $statuses = Status::all();
        return view('pages.product.create', compact('clients', 'developers', 'statuses'));
    }

    /**
     * @param ProductRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(ProductRequest $request)
    {
        $data = [
            'name' => $request->input('name'),
            'developer_id' => $request->input('developer_id'),
            'client_id' => $request->input('client_id'),
            'description' => $request->input('description'),
        ];
        if($request->has('files')){
            $data['files'] = $request->input('files');
        }
        $arrayStatusesDeadline = [];
        $arrayStatusesReport = [];
        if($request->filled('statuses')){
            foreach ($request->input('statuses') as $key=>$value){
                $arrayStatusesDeadline[$key] = Carbon::parse($value)->timestamp;
                $arrayStatusesReport[$key] = null;
            }
            $data['status_deadline'] = $arrayStatusesDeadline;
            $data['status_report'] = $arrayStatusesReport;
        }else{
            $statuses = Status::all();
            foreach ($statuses as $status){
                $arrayStatusesReport[$status->name] = null;
            }
            $data['status_report'] = $arrayStatusesReport;
        }


        $product = Product::create($data);
        if($product){
            return back()
                ->with('success',['text'=>'Product Successfully Added!', 'id'=>$product->id]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $statuses = Status::all();
        $product = Product::find($id);
        return view('pages.product.show', compact('statuses', 'product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::find($id);
        $clients = Client::all();
        $developers = User::where('role', '=', User::ROLE_DEVELOPER)->get();
        $statuses = Status::all();
        return view('pages.product.edit', compact('product', 'clients', 'developers', 'statuses'));
    }

    /**
     * @param ProductRequest $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(ProductRequest $request, $id)
    {
        $product = Product::find($id);
        $data = [
            'name' => $request->input('name'),
            'developer_id' => $request->input('developer_id'),
            'client_id' => $request->input('client_id'),
            'description' => $request->input('description'),
        ];

        $arrayStatusesDeadline = [];
        if($request->filled('statuses')){
            foreach ($request->input('statuses') as $key=>$value){
                $arrayStatusesDeadline[$key] = Carbon::parse($value)->timestamp;
            }
            $data['status_deadline'] = $arrayStatusesDeadline;
        }

        if($request->has('files')){
            if(!empty($product->files)){
                foreach ($product->files as $file){
                    if(!in_array($file, $request->input('files'))){
                        $this->service->deleteFile($file);
                    }
                }
            }
            $data['files'] = $request->input('files');

        } else {
            if(!empty($product->files)){
                foreach ($product->files as $file){
                    $this->service->deleteFile($file);
                }
            }
            $data['files'] = null;
        }
        $product->update($data);
        return back()
            ->with('success',['text'=>'Product Successfully Update!', 'id'=>$product->id]);
    }

    /**
     * @param Request $request
     * @param $id
     * @return \Illuminate\Http\JsonResponse|\Illuminate\Http\RedirectResponse
     */
    public function destroy(Request $request, $id)
    {
        $product = Product::find($id);
        $product->delete();
        if($request->ajax()){
            return response()->json(['status'=> 'ok']);
        }
        return redirect()->route('products.index')
            ->with('success', 'Product delete successfully!');
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     * @throws \Throwable
     */
    public function UploadFile(Request $request){
        $year = Carbon::now()->year;
        $pathProduct = 'products/'.$year;
        if($request->file('file')->isValid()){
            $name = $request->file('file')->getClientOriginalName();
            $path = 'uploads/'.$request->file('file')->storeAs($pathProduct, $name);
            $html = view('common.upload.file_product', compact('name', 'path'))->render();
            return response()->json(['success'=> true, 'html'=> $html]);
        }
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function deleteFile(Request $request )
    {
        if($request->has('file')){
            $this->service->deleteFile($request->input('file'));
            return response()->json(['success'=> true]);
        }
    }

    public function updateStatus(Request $request, $id){

        $product = Product::find($id);
        $status = $request->input('status');
        $status_date = strtotime($request->input('status_date'));
        if($status == Status::CONFIRM){
            $product->start_date = $status_date;
        }
        $arrayStatuses = $product->status_report;
        $arrayStatuses[$status] = $status_date;
        $product->status_report = $arrayStatuses;
        $product->status = $status;
        $product->save();
        return back();
    }

}

resources/views/pages/product/list.blade.php
@extends('layouts.layouts')

@section('content')

    @if (session('success'))
        <div class="alert alert-success status_alert" id="status_alert">
            {{ session('success') }}
        </div>
    @endif
<div class="page-suppliers">
    <div class="page-title">
        <div class="title_left">
            <h3>{{__('List of Products')}}</h3>
        </div>
        <div class="title_right">
            <div class="row">
                <div class="col-md-12">
                    <form action="{{ route('products.index') }}" method="get">
                        <div class="form-group pull-right top_search">
                            <div class="input-group">
                                <input type="text" class="form-control" value="{{ $search }}" name="search" placeholder="Search for...">
                                <span class="input-group-btn">
                              <button class="btn btn-default" type="submit">Go!</button>
                            </span>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-md-12">
            <div class="x_panel">
                <div class="row">
                    <div class="col-md-6">
                        @if($products->isNotEmpty())
                        <div class="align-items-center">
                            @php
                                $count = $products->count();
                                $perPage = $products->perpage();
                                $currentPage = $products->currentPage();
                                $total = $products->total();
                                $showing = $currentPage == 1? 1: $perPage * ($currentPage-1);
                            @endphp
                            <span style="margin-right: 5px;"> Showing {{ $showing  }} - {{ $currentPage == 1? $count: $showing+$count }} of {{ $total }}  Products</span>
                        </div>
                        @endif
                    </div>
                    <div class="col-md-6">
                        <div class="pull-right">
                            <a href="{{route('products.create')}}" class="btn btn-sm btn-primary" id="add_supplier">{{__('Add New product')}}</a>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                @if($products->isNotEmpty())
                <!-- start project list -->
                    <table class="table table-striped projects">
                        <thead>
                        <tr>
                            <th>Number:</th>
                            <th>Product:</th>
                            <th>Status:</th>
                            <th>Start:</th>
                            <th>Developer:</th>
                            <th>Client:</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($products as $product)
                        <tr>
                            <td>{{ $product->id }}</td>
                            <td>{{ $product->name }}</td>
                            <td>{{ empty($product->status)? 'no-status': $product->productStatus->description }}</td>
                            <td>{{ empty($product->start_date)? '':$product->start_date->format('d.m.Y') }}</td>
                            <td>{{ $product->developer->name }}</td>
                            <td>{{ $product->client->name }}</td>
                            <td>
                                <div class="td_actions">
                                    <a href="{{ route('products.show',$product->id)}}" title="view" class="btn btn-success btn-xs" ><i class="fa fa-eye"></i></a>
                                    <a href="{{ route('products.edit',$product->id)}}" title="edit" class="btn btn-primary btn-xs edit_post" ><i class="fa fa-pencil"></i></a>
                                    <form action="{{ route('products.destroy', $product->id)}}" method="post">
                                        {{ csrf_field() }}
                                        @method('DELETE')
                                        <button class="btn btn-danger btn-xs delete_post"><i class="fa fa-trash-o"></i> </button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                        @endforeach
                        </tbody>
                    </table>

                    {{ $products->links() }}
                    <!-- end project list -->
                    @else
                        <div>Nothing found</div>
                    @endif
                </div>
            </div>
        </div>
    </div>

</div>

@endsection

resources/views/pages/product/show.blade.php
@extends('layouts.layouts')

@section('content')

    @if (session('success'))
        <script>
            show_modal = true;
        </script>
    @else
        <script>
            show_modal = false;
        </script>
    @endif
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-10">
                    <h4>Product - {{ $product->name }} - №{{ $product->id }}</h4>
                </div>
                <div class="col-md-2">
                    @can('admin')
                    <div class="td_actions">
                        <a href="{{ route('products.edit',$product->id)}}" title="edit" class="btn btn-primary btn-xs edit_post" ><i class="fa fa-pencil"></i></a>
                        <form action="{{ route('products.destroy', $product->id)}}" method="post">
                            {{ csrf_field() }}
                            @method('DELETE')
                            <button class="btn btn-danger btn-xs delete_post"><i class="fa fa-trash-o"></i> </button>
                        </form>
                    </div>
                     @endcan
                </div>
            </div>
            <div class="x_panel">
                <div class="x_content product_show">
                    <div class="row">
                        <div class="col-md-6 col_border_right">
                            <h6>Product Name: {{ $product->name }}</h6>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="user_block">
                                        <div class="img_block">
                                            <img src="{{ $product->developer->avatar? asset($product->developer->avatar): asset('uploads/users/default_avatar.png') }}" alt="">
                                        </div>
                                        <div class="user_info">
                                            <div class="title">Developer - {{ $product->developer->name }}</div>
                                            <div class="email"><i class="fa fa-envelope"></i> {{ $product->developer->email }}</div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="user_block">
                                        <div class="img_block">
                                            <img src="{{ $product->client->avatar? asset($product->client->avatar): asset('uploads/users/default_avatar.png') }}" alt="">
                                        </div>
                                        <div class="user_info">
                                            <div class="title">Client - {{ $product->client->name }}</div>
                                            <div class="email"><i class="fa fa-envelope"></i> {{ $product->client->email }}</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div>
                                        <h4>Description:</h4>
                                        <div  class="desc_product" >{{ $product->description }}</div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Attach additional materials:</label>
                                        <div class="files_wrap" id="files_wrap">
                                            @if($product->files)
                                                @foreach($product->files as $file)
                                                    <a href="{{ asset($file) }}"  download class="file_block">
                                                        <div class="file_name_block">
                                                            <span class="file_name">{{ pathinfo($file)['basename'] }}</span>
                                                        </div>
                                                    </a>
                                                @endforeach
                                            @endif
                                        </div>
                                    </div>


                                </div>
                            </div>
                        </div>
                        @if($product->status_deadline)
                        <div class="col-md-3">
                            <h3>Deadline</h3>
                            <div class="wizard_verticle">
                                <ul class="wizard_steps anchor status_list">
                                    @foreach( $statuses as $status)
                                        <li>
                                            <a  class="status_icon selected">
                                                <span class="step_no"><i class="fa {{ $status->icon }}" ></i></span>
                                            </a>
                                            <div class="date_wrap">
                                                <div class="step_descr">
                                                    {{ $status->description }}<br>
                                                </div>
                                                <div class="status_date">
                                                    {{ $product->getDateStatus($product->status_deadline[$status->name]) }}
                                                </div>
                                            </div>
                                        </li>
                                    @endforeach
                                </ul>
                            </div>
                        </div>
                        @endif
                         @php $index = optional($product->productStatus)->index?: 0  @endphp
                        <div class="col-md-3">
                            <h3>Status Report</h3>
                            <div class="wizard_verticle">
                                <ul class="wizard_steps anchor status_list">
                                    @foreach( $statuses as $status)
                                        <li>
                                            <a  class="status_icon {{ $status->index <= $index? 'selected': 'disabled' }}">
                                                <span class="step_no"><i class="fa {{ $status->icon }}" ></i></span>
                                            </a>
                                            <div class="date_wrap">
                                                <div class="step_descr">
                                                    @if($status->index === $index)
                                                    <strong>{{ $status->description }}</strong>
                                                    @else
                                                        {{ $status->description }}
                                                    @endif
                                                </div>
                                                <div class="status_date">
                                                    @if($product->status_report[$status->name])
                                                        @if($status->index === $index)
                                                            <strong>{{ $product->getDateStatus($product->status_report[$status->name]) }}</strong>
                                                        @else
                                                            {{ $product->getDateStatus($product->status_report[$status->name]) }}
                                                        @endif
                                                    @elseif(($index + 1) == $status->index)
                                                        <div class="step_completed"><i class="fa fa-check"></i> Mark this step completed.</div>
                                                        <form action="{{ route('update.status', $product->id) }}" method="post" class="update_status_form">
                                                            {{ csrf_field() }}
                                                            <input type="hidden" name="status" value="{{ $status->name }}">
                                                            <fieldset>
                                                                <div class="control-group">
                                                                    <div class="controls">
                                                                        <div class="col-md-11 xdisplay_inputx form-group row has-feedback">
                                                                            <input
                                                                                    type="text"
                                                                                    class="form-control has-feedback-left calendar_status_up"
                                                                                    name="status_date"
                                                                                    value=""
                                                                            >
                                                                            <span class="fa fa-calendar-o form-control-feedback left" aria-hidden="true"></span>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </fieldset>
                                                            <div class="button_wrap">
                                                                <button class="btn btn-primary btn-sm"><i class="fa fa-check"></i> Save</button>
                                                            </div>
                                                        </form>
                                                    @endif
                                                </div>
                                            </div>
                                        </li>
                                    @endforeach
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection