routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::middleware(['auth'])->group(function () {

    Route::get('/', 'HomeController@index')->name('home');

    Route::resource('developers', 'DeveloperController');
    Route::resource('clients', 'ClientController')->middleware('checkAdmin');
    Route::resource('products', 'ProductController');
    Route::resource('admins', 'AdminController')->middleware('checkSuperAdmin');
    Route::resource('users', 'UserController')->middleware('checkSuperAdmin');
    Route::any('kpi', 'KpiController@index')->name('kpi')->middleware('checkAdmin');

    //home
    Route::post('filter_status', 'HomeController@filterStatus')->name('filter.status');
    Route::post('search_home', 'HomeController@searchProduct')->name('search.home');
    Route::post('load_products', 'HomeController@loadProducts');

    //upload product file
    Route::post('uploads/product/file', 'ProductController@uploadFile');
    //delete product file
    Route::post('delete/product/file', 'ProductController@deleteFile');
    //update status
    Route::post('update/product/status/{id}', 'ProductController@updateStatus')->name('update.status');


});

app/Http/Controllers/DeveloperController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\DeveloperRequest;
use App\Http\Requests\DeveloperUpdateRequest;
use App\Models\Product;
use App\Models\Status;
use App\Models\User;
use App\Services\KpiServices;
use App\Services\Upload\UploadFileService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class DeveloperController extends Controller
{

    private $service;
    private $kpiService;
    public function __construct(UploadFileService $service, KpiServices $kpiService)
    {
        $this->middleware('checkAdmin')->only(['index', 'create', 'update', 'store','destroy','edit']);
        $this->service = $service;
        $this->kpiService = $kpiService;
    }

    /**
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Request $request)
    {
        $search = '';
        if ($request->filled('search')){
            $search = $request->input('search');
            $developers = User::where([['name', 'like', '%'.$search.'%'], ['role', '=', User::ROLE_DEVELOPER]])
                ->latest()
                ->paginate(15);
        } else {
            $developers = User::where('role', '=', User::ROLE_DEVELOPER)
                ->latest()
                ->paginate(15);
        }


        return view('pages.developer.list', compact('developers', 'search'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.developer.create');
    }

    /**
     * @param DeveloperRequest $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(DeveloperRequest $request)
    {
        $data = [
            'name' => $request->input('name'),
            'email' => $request->input('email'),
            'role' => User::ROLE_DEVELOPER,
            'description' => $request->input('description'),
            'password' => Hash::make($request->input('password')),
        ];
        if($request->filled('avatar')){
            $avatar = $this->service->uploadAvatar($request);
            $data['avatar'] = $avatar;
        }
        $developer = User::create($data);

        return back()
            ->with('success',['text'=>'Developer Successfully Added!', 'id'=>$developer->id]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = auth()->user();
        if($user->role == User::ROLE_ADMIN || $user->role == User::ROLE_SUPER_ADMIN || $user->id == $id ){
            $developer = User::find($id);
            $clients = Product::where('developer_id', '=', $developer->id)
                ->groupBy('client_id')
                ->paginate(2);
            $clients_ids = [];
            if($clients->isNotEmpty()){
                foreach ($clients as $client){
                    $clients_ids[] = $client->client_id;
                }
            }
            $items = Product::where('developer_id','=',$developer->id)
                ->whereIn('client_id',$clients_ids)
                ->get();
            $products = $items->groupBy('client_id');
            $count_products = Product::where('developer_id','=',$developer->id)->count();
            $products_goods = Product::where([['status', '=', Status::GOODS],['developer_id', '=', $developer->id]])->get();
            $arrayTime = $this->kpiService->developerTime($products_goods);
            $statuses = Status::all();

            return view('pages.developer.show', compact('clients', 'count_products', 'arrayTime', 'products', 'developer', 'statuses'));
        } else {
            return redirect()->route('home');
        }

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $developer = User::find($id);
        return view('pages.developer.edit', compact('developer'));
    }

    /**
     * @param DeveloperUpdateRequest $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(DeveloperUpdateRequest $request, $id)
    {
        $developer = User::find($id);
        $data = [
            'name' => $request->input('name'),
            'email' => $request->input('email'),
            'description' => $request->input('description'),
        ];

        if($request->filled('password') ){
            $data['password'] = Hash::make($request->input('password'));
        }
        if($request->filled('del_avatar')){
            $this->service->deleteFile($developer->avatar);
            $developer->avatar = null;
        }
        if($request->filled('avatar')){
            $avatar = $this->service->uploadAvatar($request);
            $data['avatar'] = $avatar;
        }

        $developer->update($data);

        return back()
            ->with('success',['text'=>'Developer Successfully Added!', 'id'=>$developer->id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $developer = User::find($id);
        $this->service->deleteFile($developer->avatar);
        $developer->delete();
        return redirect('developers')->with('success','Developer deleted successfully');
    }
}

resources/views/pages/developer/create.blade.php
@extends('layouts.layouts')

@section('content')

    @if (session('success'))
        <script>
            show_modal = true;
        </script>
    @else
        <script>
            show_modal = false;
        </script>
    @endif
    <div class="row">
        <div class="col-md-6">
            <div>
                <h4>{{ __('Add New Developer') }}</h4>
            </div>
            <div class="x_panel">
                <div class="x_title">
                    <h6>Details</h6>
                </div>
                <div class="x_content">
                    <form id="create-developer-form" action="{{ route('developers.store') }}" method="POST" style="max-width: 800px">
                        {{ csrf_field() }}
                        <input type="hidden" name="avatar" value="{{ old('avatar') }}" id="input_avatar">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="photo_wrapper">
                                    <div class="img_block text-center">
                                        <img id="img_avatar"
                                             class="img_avatar"
                                             src="{{ empty(old('avatar'))? asset('uploads/users/default_avatar.png'): old('avatar') }}"
                                             alt="avatar"
                                        >
                                    </div>
                                    <div class="button_block">
                                        <input type="file" id="file_upload" name="file" accept="image/jpeg,image/png" style="display: none">
                                        <label for="file_upload" id="button_file_upload" class="btn btn-secondary btn-sm"><i class="fa fa-pencil"></i></label>
                                        <button class="btn btn-secondary btn-sm"
                                                id="delete_file"
                                                type="button"
                                                data-default_avatar="{{ asset('uploads/users/default_avatar.png') }}"
                                        ><i class="fa fa-trash-o"></i></button>
                                    </div>
                                    <div id="error_block_file"></div>
                                </div>
                            </div>
                            <div class="col-md-8">
                                <div class="form-group">
                                    <label for="name">Name * </label>
                                    <input type="text" id="name" name="name" class="form-control" value="{{ old('name') }}" />
                                    <span class="text-danger">{{ $errors->first('name') }}</span>
                                </div>
                                <div class="form-group">
                                    <label for="email">Email * </label>
                                    <input type="email" id="email" class="form-control" name="email" value="{{ old('email') }}" />
                                    <span class="text-danger">{{ $errors->first('email') }}</span>
                                </div>
                                <div class="form-group">
                                    <label for="password">Password * </label>
                                    <input type="password" id="password" class="form-control" name="password" />
                                    <span class="text-danger">{{ $errors->first('password') }}</span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>Description(20 chars min):</label>
                                    <textarea name="description" class="form-control" placeholder="Description of good" >{{ old('description') }}</textarea>
                                    <span class="text-danger">{{ $errors->first('description') }}</span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="button_block">
                                    <a href="{{ route('developers.index') }}" class="btn btn-danger">Cancel</a>
                                    <button class="btn btn-primary" type="submit">Save</button>
                                </div>
                                <div class="alert_block_form" id="alert_block_form"></div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    @include('common.modals.croppie_modal')
    @include('common.modals.size_modal')
    @include('common.modals.developer_add_modal')

@endsection

resources/views/pages/developer/list.blade.php
@extends('layouts.layouts')

@section('content')

    @if (session('success'))
        <div class="alert alert-success status_alert" id="status_alert">
            {{ session('success') }}
        </div>
    @endif
<div class="page-suppliers">
    <div class="page-title">
        <div class="title_left">
            <h3>{{__('List of Developers')}}</h3>
        </div>
        <div class="title_right">
            <div class="row">
                <div class="col-md-12">
                    <form action="{{ route('developers.index') }}" method="get">
                        <div class="form-group pull-right top_search">
                            <div class="input-group">
                                <input type="text" class="form-control" value="{{ $search }}" name="search" placeholder="Search for...">
                                <span class="input-group-btn">
                              <button class="btn btn-default" type="submit">Go!</button>
                            </span>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-md-12">
            <div class="x_panel">
                <div class="row">
                    <div class="col-md-6">
                        @if($developers->isNotEmpty())
                        <div class="align-items-center">
                            @php
                                $count = $developers->count();
                                $perPage = $developers->perpage();
                                $currentPage = $developers->currentPage();
                                $total = $developers->total();
                                $showing = $currentPage == 1? 1: $perPage * ($currentPage-1);
                            @endphp
                            <span style="margin-right: 5px;"> Showing {{ $showing  }} - {{ $currentPage == 1? $count: $showing+$count }} of {{ $total }}  Developers</span>
                        </div>
                         @endif
                    </div>
                    <div class="col-md-6">
                        <a href="{{route('developers.create')}}" class="btn btn-sm btn-primary pull-right" id="add_supplier">{{__('Add New Developer')}}</a>
                    </div>

                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                @if($developers->isNotEmpty())
                <!-- start project list -->
                    <table class="table table-striped projects">
                        <thead>
                        <tr>
                            <th style="width: 15%;" >Avatar</th>
                            <th>Name</th>
                            <th>Email</th>

                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($developers as $developer)
                        <tr>
                            <td><img src="{{ isset($developer->avatar)? asset($developer->avatar) : asset('uploads/users/default_avatar.png') }}" alt="" style="width: 60px;"></td>
                            <td>{{$developer->name}}</td>
                            <td>{{$developer->email}}</td>
                            <td>
                                <div class="td_actions">
                                    <a href="{{ route('developers.show', $developer->id) }}" class="btn btn-success btn-xs">
                                        <i class="fa fa-eye"></i>
                                         Developer page
                                    </a>
                                    <a href="{{ route('developers.edit',$developer->id)}}" class="btn btn-primary btn-xs edit_post" ><i class="fa fa-pencil"></i></a>
                                    <form action="{{ route('developers.destroy', $developer->id)}}" method="post">
                                        {{ csrf_field() }}
                                        @method('DELETE')
                                        <button class="btn btn-danger btn-xs delete_post"><i class="fa fa-trash-o"></i> </button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                        @endforeach
                        </tbody>
                    </table>
                {{ $developers->links() }}
                    <!-- end project list -->
                    @else
                        <div>Nothing found</div>
                    @endif
                </div>
            </div>
        </div>
    </div>

</div>

@endsection

resources/views/pages/developer/show.blade.php
@extends('layouts.layouts')

@section('content')
    <div class="developer_page" id="developer_page" data-developer="{{ 'developer_'.$developer->id }}">
        @include('common.developer_top')

        <div class="row">
            <div class="col-md-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Clients</h2>
                        <div class="pull-right">
                           @can('admin') <a href="{{ route('clients.create') }}" class="btn btn-primary">Add New Client</a> @endcan
                        </div>
                        <div class="clearfix"></div>
                    </div>

                    <div class="x_content">
                        <div id="products_wrap">
                            @if($clients->isNotEmpty())
                                <div class="clients_list" >
                                    <ul class="developers_clients_list">
                                        @foreach($clients as $client)
                                            <li class="client_wrap {{ 'tab_client_'.$client->id }}" data-class="{{ 'tab_client_'.$client->id }}">
                                                <div class="client_top_block">
                                                    <div class="title">{{ $client->client->name }}</div>
                                                    <div class="action_block td_actions">
                                                        @can('admin')
                                                        <a href="{{ route('clients.edit',$client->client->id)}}" class="btn btn-primary btn-sm edit_post" ><i class="fa fa-pencil"></i></a>
                                                        @endcan
                                                        <button class="caret_button"><i class="fa fa-caret-down"></i></button>
                                                    </div>
                                                </div>
                                                @if(!empty($products[$client->client_id]))
                                                    <ul class="products_list">
                                                        @foreach($products[$client->client_id] as $product)
                                                            <li class="product_wrap client_wrap {{ 'tab_product_'.$product->id }}" data-class="{{ 'tab_product_'.$product->id }}">
                                                                <div class="product_top_block client_top_block">
                                                                    <div class="title">{{ $product->name }}</div>
                                                                    <div class="action_block td_actions">
                                                                        <a href="{{ route('products.show',$product->id)}}" title="view" class="btn btn-success btn-sm" ><i class="fa fa-eye"></i></a>
                                                                        @can('admin')
                                                                        <a href="{{ route('products.edit',$product->id)}}" title="edit" class="btn btn-primary btn-sm edit_post" ><i class="fa fa-pencil"></i></a>
                                                                        <form action="{{ route('products.destroy', $product->id)}}" method="post" class="form_delete_product">
                                                                            {{ csrf_field() }}
                                                                            @method('DELETE')
                                                                            <button class="btn btn-danger btn-sm delete_post"><i class="fa fa-trash-o"></i> </button>
                                                                        </form>
                                                                        @endcan
                                                                        <button class="caret_button"><i class="fa fa-caret-down"></i></button>
                                                                    </div>
                                                                </div>
                                                                <div class="row product_block x_title">
                                                                    <div class="col-md-3">
                                                                        <h4> {{ $product->client->name }} - {{ $product->name }}</h4>
                                                                        <ul class="detail_order">
                                                                            <li>
                                                                                <span class="label">Product Number: </span>
                                                                                <span class="value"><strong>{{ $product->id }}</strong></span>
                                                                            </li>
                                                                            <li>
                                                                                <span class="label">Status: </span>
                                                                                <span class="value"><strong>{{ empty($product->status)? 'no-status': $product->productStatus->description }}</strong></span>
                                                                            </li>
                                                                            <li>
                                                                                <span class="label">Start: </span>
                                                                                <span class="value"><strong>{{ $product->created_at->format('d.m.Y') }}</strong></span>
                                                                            </li>
                                                                            <li>
                                                                                <span class="label">Product: </span>
                                                                                <span class="value"><strong>{{ $product->name }}</strong></span>
                                                                            </li>
                                                                            <li>
                                                                                <span class="label">Developer: </span>
                                                                                <span class="value"><strong>{{ $product->developer->name }}</strong></span>
                                                                            </li>
                                                                            <li>
                                                                                <span class="label">Client: </span>
                                                                                <span class="value"><strong>{{ $product->client->name }}</strong></span>
                                                                            </li>
                                                                        </ul>
                                                                    </div>
                                                                    <div class="col-md-9">
                                                                        <div class="form_wizard wizard_horizontal">
                                                                            <ul class="wizard_steps anchor">
                                                                                @php $width = round(100/count($statuses)) @endphp
                                                                                @php $index = optional($product->productStatus)->index?: 0  @endphp
                                                                                @foreach( $statuses as $status)
                                                                                    <li style="width: {{$width}}%;">
                                                                                        <a  class="{{ $status->index <= $index? 'selected': 'disabled' }}">
                                                                                            <span class="step_no"><i class="fa {{ $status->icon }}" ></i></span>
                                                                                            <span class="step_descr">
                                                {{ $status->description }}<br>
                                                <small>{{ !empty($product->status_report[$status->name])? $product->getDateStatus($product->status_report[$status->name]) :'' }}</small>
                                                </span>
                                                                                        </a>
                                                                                    </li>
                                                                                @endforeach
                                                                            </ul>
                                                                        </div>
                                                                    </div>
                                                                    <div class="clearfix"></div>
                                                                </div>
                                                            </li>
                                                        @endforeach
                                                    </ul>
                                                @endif
                                            </li>
                                        @endforeach
                                    </ul>

                                </div>
                                {{ $clients->links() }}
                            @else
                                <div>Nothing found</div>
                            @endif
                        </div>
                    </div>


                </div>
            </div>
        </div>

    </div>
@endsection